spring.application.name=backend
# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_celulares
spring.datasource.username=postgres
spring.datasource.password=6032
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Puerto del servidor
server.port=8081

spring.config.import=optional:classpath:application-secrets.properties
mercadopago.access-token=${mercadopago.access-token}
mercadopago.public-key=${mercadopago.public-key}