spring.application.name=backend

# Base de datos
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${DB_USERNAME:postgres.gtepzrkvhrvuacunwmfm}
spring.datasource.password=${DB_PASSWORD:5MYgnoqHs6KDDx2x}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor
server.port=8081

# JWT
jwt.secret=${JWT_SECRET:tienda-celulares-secret-key-super-segura-2024-min32bytes}
jwt.expiration=${JWT_EXPIRATION:86400000}

# CORS
app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:3000}

# MercadoPago
spring.config.import=optional:classpath:application-secrets.properties
mercadopago.access-token=${MP_ACCESS_TOKEN:${mercadopago.access-token:}}
mercadopago.public-key=${MP_PUBLIC_KEY:${mercadopago.public-key:}}

# Spring Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Gemini API (Chatbot IA)
gemini.api.key=${GEMINI_API_KEY:}

# Twilio (Bot WhatsApp)
twilio.account-sid=${TWILIO_ACCOUNT_SID:}
twilio.auth-token=${TWILIO_AUTH_TOKEN:}
twilio.phone-number=${TWILIO_PHONE_NUMBER:}